### ISSUE TITLE
Error on `npm run dev`

### ISSUE THREAD

**Issue by jycouet** [jldec/paraglide#1]
![Capture d’écran 2024-01-09 à 09 27 36](https://github.com/jldec/paraglide/assets/5312607/b6fa880c-34ce-45a4-8f29-bbef8d960fa0)

here is the repro: https://www.sveltelab.dev/?provider=github&owner=jldec&repo=paraglide&branch=main&path=

**Comment by jldec** [comment]
This has been fixed for sveltelab.dev
thank you @jycouet
